# Generated by Django 3.2.11 on 2022-02-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_download_app', '0002_auto_20220131_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(choices=[('SL', 'Sales'), ('MK', 'Marketing'), ('RD', 'Research And Develop'), ('IT', 'Information Technology')], max_length=25),
        ),
    ]
